name: bruceboard
description: A Sports Pool Game App
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
# 2(0.0.10) : Updated Player Name input, split Fname/LName & Default initials. (Published: 2023/10/04)
# 3(0.0.11) : Deployed to Android 2023/10/06 - Closed Testing
#   Updated App Name to AA Bruce Board
#   Added Football Icon https://www.geeksforgeeks.org/flutter-changing-app-icon/
# 4(0.0.12) : WIP
#   Refactored code.
# 14(1.1.0): Added gameDate to Data Model.
# 14(1.1.1): Cleaned up Settings - Removed old scoring page.
# 15(1.1.2): Fixed scrolling on iPad, Added Approval settings,
#  update fsDoc.Update to merge to fix totalisers and next numbers getting overwritten.
#  update Player.Update to retain existing values when updating Player
# 16(1.1.3) Locked Score once credits distributed
# Changed "Series" to "Group" for clarity
# 18(1.1.5) Added SafeAreas to missing Screens
# 19(1.1.6) Positioning/Sizes on GameBoard for Score
#   Added variable to avoid multiple Auto Processing.
#   Added Summary page for Games
#   Added Remaining Credits to Message Request
# 20(1.1.7) Paused adds for deploy to Apple
#   Added Status to Account to indicated active.
# 21(1.1.8) Restricted Player Select to active players
#   Trim Name on entry and profile chnages
# 22(1.1.9) Added IOS Ads number and adds to About and Home
# 23(1.2.0) Added SquareStatus to Grid (Free,Requested,Taken) for Cloud Functions
#   Excluded ads on Web deploys
# 1.2.1(24) Bug Fixes
#   Fixed Credit error when filling squares and dont run out of credits.
#   Fixed reset square on double request.
# 1.2.2(25) Bug Fixes
#   Added Ads, Cleaned up Game Page & Game Summary Page
# 1.2.3(26) Bug Fixes
#  General Bug Fixes.
#  Fixed "Doman" on signin.
#  Added Verify Prompt to SignUp
#  Added Default Cid for Series to pick where Community Credits go.
# 1.2.4(27)
#  Added Show/No Show to passwords
#  Hardcoded Excluded Player to 1000
#  Added Square to Audit
#  Removed Splits menu option from Game Board
#  Stopped Debiting from exclude player
#  Trimmed Email on Sign_In and Sign_Up
#  Updated Credits on Membership page when returning from Games
#  Updated the About Page with additional info
#  Added Harvey Balls to Game Tile to show amount full
#  Setup Public Games
#  Created new UX (access via Settings)
# 1.2.5(28)
#  Minor display change
#  Quick Local Disable square to avoid re-select on slow network
#  Added Log to Square Rejected (206) (also fixed Cloud Function to not
#    increment SquaresPicked for "Requested" vs "Taken")
# 1.2.6(29)
#  Added Audit Log Reports for Games (Summary/Detail)
# 1.2.7(30) Fixes on Apple
#  Report Width overflow fixed.
#  Default to New Interface
# 1.2.8(31)
#  Added Totals to Game Audit Reports
# 1.2.9 (32)
#  Added Charity Name and CharityNo to Communities
#  Added Community Summary Report
#  Added Membership Level
#  Renamed Games/Pools to Boards
#  Added ability to message members in a community
version: 1.2.9+32

environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  # shared_preferences: is dependency of adaptive_theme so also included there.
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0
  settings_ui: ^2.0.2
  fluttericon: ^2.0.0
  flutter_settings_screens: ^0.3.3-null-safety+2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  intl: ^0.19.0
  #  flutter_email_sender: ^6.0.1
  adaptive_theme: ^3.4.0
  provider: ^6.0.5
  flutter_any_logo: ^1.1.1
  flutter_svg: ^2.0.10+1
  google_mobile_ads: ^5.1.0
  url_launcher: ^6.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/cfl/
    - assets/harveyballs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
